### ISSUE TITLE
Not adding Graduate Student or PhD Graduate pages

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Criminal-Justice#4]
I have been leaving out the graduate student bio pages for all programs as we have not discussed if these will be present in Jekyll. Criminal Justice, GUS, Sociology and Political Science (and a few others) all have these pages of content. 

** I have recommended to faculty in the past that grad students should set up personal pages in sites.temple.edu**

**Comment by tu-chill** [comment]
Leave them out for now. I know there will be an effort to use elements for Ph.D. students in the future. This content won't get added until after we are pulling data from elements. For now, it will be a won't fix.
