### ISSUE TITLE
Graduate Faculty Header

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Criminal-Justice#7]
The graduate faculty header is not aligning correctly. It has been pushed over to the right of the page under the sidebar. Just the header portion. 
https://develop.cla.temple.edu/criminal-justice/graduate/

**Comment by tu-chill** [comment]
k. i can fix this pretty quick when i log back in


c.hill@temple.edu<mailto:c.hill@temple.edu>
marketing technology


On May 25, 2018, at 11:56 AM, Camille Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


The graduate faculty header is not aligning correctly. It has been pushed over to the right of the page under the sidebar. Just the header portion.

**Comment by CVE82** [comment]
Awesome thanks no rush, was just making the issue so I didn't forget =)

**Comment by tu-chill** [comment]
magic fixed this.
