### ISSUE TITLE
New Layout

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Criminal-Justice#8]
The new layout has stripped out and won't let me add back in bullet points on all pages. Can we fix this next week? Thanks and Happy Camping!

**Comment by tu-chill** [comment]
👍

c.hill@temple.edu<mailto:c.hill@temple.edu>
marketing technology


On May 25, 2018, at 12:33 PM, Camille Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


The new layout has stripped out and won't let me add back in bullet points on all pages. Can we fix this next week? Thanks and Happy Camping!

**Comment by tu-chill** [comment]
I think this is fixed. I don't remember fixing it though.
